services:
  divnum-discord-bot:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: divnum-discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      # Persist game data and weekly plans
      - ./data:/app/data
      # Optional: Mount logs directory
      - ./logs:/app/logs
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  bot-network:
    driver: bridge

volumes:
  bot-data:
    driver: local