# Override file for local development
# This file is automatically loaded with docker-compose.yml
services:
  divnum-discord-bot:
    # Override for development - mount source code
    volumes:
      - ./src:/app/src:ro
      - ./data:/app/data
      - ./logs:/app/logs
    # Enable development mode
    environment:
      - NODE_ENV=development
      - DEBUG=true
    # Add development labels
    labels:
      - "dev.environment=local"
      - "dev.purpose=discord-bot-development"