name: Publication Docker

# Déclenche la CI sur push de tags et sur la branche main
on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Permet de déclencher manuellement

env:
  # Nom de l'image
  IMAGE_NAME: divnum-discord-bot
  # Registres Docker
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  GHCR_REGISTRY: ghcr.io

jobs:
  # Job de build et test
  build-and-test:
    name: Build et Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 📦 Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📚 Installation des dépendances
        run: npm ci

      - name: 🔍 Vérification du formatage
        run: npm run format:check

      - name: 🔎 Lint du code
        run: npm run lint

      - name: 🔧 Vérification des types TypeScript
        run: npm run type-check

      - name: 🏗️ Build de l'application
        run: npm run build

      - name: 📤 Upload des artefacts de build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          retention-days: 7

  # Job de publication Docker
  docker-publish:
    name: Publication Image Docker
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 🔐 Configuration de QEMU
        uses: docker/setup-qemu-action@v3

      - name: 🔧 Configuration de Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 📝 Extraction des métadonnées Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: 🔑 Connexion à GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔑 Connexion à Docker Hub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request' && secrets.DOCKER_HUB_TOKEN != ''
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 🐳 Build et Push de l'image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ steps.meta.outputs.version }}


      - name: 📊 Affichage des informations de l'image
        run: |
          echo "### 🐳 Images Docker Publiées" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Tags créés :**" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Digests :**" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "SHA: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  # Job optionnel: Scan de sécurité
  security-scan:
    name: Scan de Sécurité
    needs: docker-publish
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 🔍 Scan de vulnérabilités avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.GHCR_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: 📤 Upload des résultats vers GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: 🔍 Scan de vulnérabilités (rapport console)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.GHCR_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          format: 'table'
          exit-code: '0'  # Ne pas échouer sur les vulnérabilités
          severity: 'CRITICAL,HIGH'




